### ISSUE TITLE
no login component?

### ISSUE THREAD

**Issue by zengkid** [wowsomeco/ng_dart_admin#1]
not found login page.

**Comment by wowsomeco** [comment]
Could you please elaborate on this? Do you expect the Login view only without any back end logic integrated? If so, the best thing i can think of is provide you an example of how to create one somewhere in https://ngadmin.wowsome.co/#/playground perhaps so that you can copy over the .dart along with the template files. Does that work for you?

**Comment by zengkid** [comment]
user need login page, in login page, user input username and password, if auth sucessfully, then  login to the admin site. but I don't find a page without admin layout page.

**Comment by wowsomeco** [comment]
Thanks for clarifying. I think, for now, I won't include this in the library but rather to create a sample of how you can create one on the https://ngadmin.wowsome.co/#/playground page later. the reason being is that the implementation for the back end logic for the authentication, accessibility, etc. might vary depending on ones' needs. So yeah the best thing i could do is to create a view only for it and you could take it as is or modify the template / dart files accordingly. Does that work for you?

**Comment by wowsomeco** [comment]
just created a login sample on the playground page yesterday for you to try. hope it suffices. thanks.
